*/

name: https://raw.githubusercontent.com/ziyangguilai/copy-ziye/ZIYE/Task/

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XL_URL: ${{ secrets.XL_URL }}
        XL_HEADER: ${{ secrets.XL_HEADER }}		
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ABC/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XL_URL
        run: |
          cd ~/JavaScript
          npm install
